#!/usr/bin/env bash

# Replace old virtual environment with a new empty one
#rm -rf .venv
#python3 -m venv .venv

source .venv/bin/activate

while IFS='' read -r line || [[ -n "$line" ]]; do
	pip3 install $line
done < libraries

deactivate
