#!/usr/bin/env bash

# Change into this script's directory for portability
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

source .venv/bin/activate
python3 Air_Quality/ip_address.py
deactivate
